import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SampleImage from '../public/images/sample_image.png'
import NavImage from '../public/images/Nav.png'
import NavMobileImage from '../public/images/nav_mobile.png'

export default function Home() {
  return (
    <div className={styles.wrap}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav}>
        <Image
          src={NavImage}
        />
      </div>
      <div className={styles.nav_mobile}>
        <Image
          src={NavMobileImage}
        />
      </div> 
        <div className={styles.container}>
        <a className={styles.imagebox} href='https://www.google.com/'>
          <Image
            className='image'
            id='1'
            src={SampleImage}
          />
        </a>
        <a className={styles.imagebox} href='https://www.google.com/'>
          <Image
            className='image'
            id='2'
            src={SampleImage}
          />
        </a>
        <a className={styles.imagebox} href='https://www.google.com/'>
          <Image
            className='image'
            id='3'
            src={SampleImage}
          />
        </a>
        <a className={styles.imagebox} href='https://www.google.com/'>
          <Image
            className='image'
            id='4'
            src={SampleImage}
          />
        </a>
      </div>
    </div>
  )
}
